import { NexusAgent, BuilderAgent, ResearcherAgent, CreativeAgent, AnalystAgent } from "./agents";
import { RAGWorkflow } from "./workflows";
import { NexusMCP } from "./mcp-server";
import { NexusVoiceAgent } from "./voice";
import { MODELS, AGENT_MODELS } from "./models";
import { executeTool } from "./tool-executor";
import { runCodeTool } from "./code-exec";
import { streamChat, sseSend } from "./streaming";
import { CONNECTORS, getConnectorsByCategory, getConnector } from "./connectors";
import { getEnabledPlugins, installPlugin, togglePlugin, uninstallPlugin, BUILTIN_PLUGINS } from "./plugins";
import { authenticateRequest, deleteSession, loginUser, registerUser, type Session } from "./auth";
import { checkRateLimit, getRateLimitHeaders } from "./rate-limit";
import { assertPublicHttpUrl, assertSafeObjectKey, parseJson } from "./security";
import { isAllowedChatModel } from "./models";
import { Sandbox } from "@cloudflare/sandbox";
import { createMission, getMission, listMissions, setMissionStatus, addMissionStep, setStepStatus, normalizeAgent, type MissionStatus } from "./missions";

export { NexusAgent, BuilderAgent, ResearcherAgent, CreativeAgent, AnalystAgent, RAGWorkflow, NexusMCP, NexusVoiceAgent, Sandbox };
export interface Env { AI: Ai; BROWSER: Fetcher; VECTORIZE: VectorizeIndex; DB: D1Database; BUCKET: R2Bucket; CACHE: KVNamespace; SESSIONS: KVNamespace; AI_SEARCH: any; NEXUS_AGENT: DurableObjectNamespace; BUILDER_AGENT: DurableObjectNamespace; RESEARCHER_AGENT: DurableObjectNamespace; CREATIVE_AGENT: DurableObjectNamespace; ANALYST_AGENT: DurableObjectNamespace; NEXUS_MCP: DurableObjectNamespace; VOICE_AGENT: DurableObjectNamespace; SANDBOX: DurableObjectNamespace<Sandbox>; RAG_WORKFLOW: Workflow; DOC_QUEUE: Queue<any>; ASSETS: Fetcher; }
const AGENT_MAP = { nexus: "NEXUS_AGENT", sirius: "ANALYST_AGENT", ana: "BUILDER_AGENT", nova: "RESEARCHER_AGENT", creative: "CREATIVE_AGENT", builder: "BUILDER_AGENT", researcher: "RESEARCHER_AGENT", analyst: "ANALYST_AGENT" } as const;
const AGENT_PROMPTS: Record<string, string> = { nexus: "You are Nexus, a frontier-grade AI.", sirius: "You are Sirius, Mission Control and the primary orchestrator.", ana: "You are Ana, the autonomous Builder Agent.", nova: "You are Nova, the autonomous Research Agent.", creative: "You are the Creative Agent.", builder: "You are Ana, the autonomous Builder Agent.", researcher: "You are Nova, the autonomous Research Agent.", analyst: "You are Sirius, Mission Control and the primary orchestrator." };
const AUTH_PREFIXES = ["/api/sandbox", "/api/code/", "/api/tools/execute", "/api/documents", "/api/ingest", "/api/plugins", "/api/connectors/install", "/api/connectors/installed", "/api/stats", "/api/missions", "/api/conversations", "/api/artifacts", "/api/images/", "/api/search", "/api/ai-search", "/api/projects", "/api/browser/"];
function needsAuth(path: string, method: string): boolean { if (AUTH_PREFIXES.some((p) => path === p || path.startsWith(p))) return true; if (path.startsWith("/api/connectors/") && method === "DELETE") return true; return false; }
function json(data: unknown, status = 200, extra: Record<string, string> = {}): Response { return new Response(JSON.stringify(data), { status, headers: { "Content-Type": "application/json", ...extra } }); }
function httpError(err: unknown): Response { const message = err instanceof Error ? err.message : "Request failed"; const status = typeof (err as { status?: number })?.status === "number" ? (err as { status: number }).status : 400; return json({ error: message }, status); }
function requireSession(session: Session | null): Session { if (!session) throw Object.assign(new Error("Authentication required"), { status: 401 }); return session; }
function withUserHeader(request: Request, userId: string): Request { const headers = new Headers(request.headers); headers.set("X-Nexus-User-Id", userId); return new Request(request, { headers }); }
export default { async fetch(request: Request, env: Env, _ctx: ExecutionContext): Promise<Response> { const url = new URL(request.url); const path = url.pathname; if (!path.startsWith("/api/") && path !== "/mcp" && !path.startsWith("/voice")) { if (env.ASSETS) return env.ASSETS.fetch(request); return new Response("Static assets not configured. Add assets.directory in wrangler.jsonc.", { status: 503 }); } const clientIP = request.headers.get("CF-Connecting-IP") || "unknown"; const rl = await checkRateLimit(env, clientIP); const rlH = getRateLimitHeaders(rl); if (!rl.allowed) return json({ error: "Rate limit exceeded", remaining: 0 }, 429, { "Retry-After": String(Math.max(1, Math.ceil((rl.resetAt - Date.now()) / 1000))), ...rlH }); if (path === "/mcp" || path === "/mcp/" || (path === "/voice" && request.headers.get("Upgrade") === "websocket") || (path.startsWith("/api/agent/") && request.headers.get("Upgrade") === "websocket")) { const gated = await authenticateRequest(request, env); if (!gated) return json({ error: "Authentication required" }, 401, rlH); } if (path === "/mcp" || path === "/mcp/") return env.NEXUS_MCP.get(env.NEXUS_MCP.idFromName("default")).fetch(request); if (path === "/voice" && request.headers.get("Upgrade") === "websocket") return env.VOICE_AGENT.get(env.VOICE_AGENT.idFromName("default")).fetch(request); if (path.startsWith("/api/agent/") && request.headers.get("Upgrade") === "websocket") { const agentType = path.split("/")[3]; const bindingName = AGENT_MAP[agentType as keyof typeof AGENT_MAP]; if (!bindingName) return new Response("Unknown agent", { status: 404 }); const agentId = url.searchParams.get("id") || "default"; return (env as any)[bindingName].get((env as any)[bindingName].idFromName(agentId)).fetch(withUserHeader(request, (await authenticateRequest(request, env))!.userId)); } if (needsAuth(path, request.method)) { const session = await authenticateRequest(request, env); if (!session) return json({ error: "Authentication required" }, 401, rlH); } const ok = (data: unknown, status = 200) => json(data, status, rlH); try { return await handleApi(request, env, path, url, ok, rlH); } catch (err) { const res = httpError(err); const headers = new Headers(res.headers); for (const [k, v] of Object.entries(rlH)) headers.set(k, v); return new Response(res.body, { status: res.status, headers }); } }, async queue(batch: MessageBatch<any>, env: Env): Promise<void> { for (const m of batch.messages) { try { await env.RAG_WORKFLOW.create({ params: m.body }); m.ack(); } catch (e) { console.error(e); m.retry(); } } } } satisfies ExportedHandler<Env>;

async function handleApi(request: Request, env: Env, path: string, url: URL, ok: (data: unknown, status?: number) => Response, rlH: Record<string, string>): Promise<Response> {
  const session = await authenticateRequest(request, env);
  if (path === "/api/health") return ok({ name: "nexus-ai", version: "3.0.2", status: "online", agents: ["sirius", "ana", "nova", "creative"], features: ["mcp-server", "streaming", "sandbox", "connectors", "plugins", "voice", "auth", "rate-limiting", "projects", "mission-control"], models: { chat: Object.values(MODELS.chat), vision: Object.values(MODELS.vision), imageGen: Object.values(MODELS.imageGen) }, connectors: CONNECTORS.length, plugins: BUILTIN_PLUGINS.length });
  if (path === "/api/chat" && request.method === "POST") { const body = await parseJson<{ message?: string; agent?: string; sessionId?: string; model?: string; images?: string[]; stream?: boolean }>(request); const message = String(body.message || "").trim(); if (!message) return ok({ error: "message required" }, 400); if (message.length > 8000) return ok({ error: "message too long" }, 400); const agentType = body.agent || "nexus"; const bindingName = AGENT_MAP[agentType as keyof typeof AGENT_MAP]; if (!bindingName) return ok({ error: "Unknown agent" }, 400); const modelKey = agentType === "sirius" ? "analyst" : agentType === "ana" ? "builder" : agentType === "nova" ? "researcher" : agentType; const selectedModel = (body.model && isAllowedChatModel(body.model) ? body.model : AGENT_MODELS[modelKey as keyof typeof AGENT_MODELS].primary); const sid = body.sessionId || crypto.randomUUID(); if (body.stream) { const readable = new ReadableStream({ async start(controller) { await streamChat({ model: selectedModel, systemPrompt: AGENT_PROMPTS[agentType] || AGENT_PROMPTS.nexus, messages: [{ role: "user", content: message }], agentType: modelKey, env, userId: session?.userId, onToken: (t) => sseSend(controller, "token", { token: t }), onToolCall: (tool, args) => sseSend(controller, "tool_call", { tool, args }), onToolResult: (tool, result) => sseSend(controller, "tool_result", { tool, result }), onArtifact: (a) => sseSend(controller, "artifact", a), onComplete: (fullText, usage) => { sseSend(controller, "done", { content: fullText, model: selectedModel, usage, sessionId: sid }); controller.close(); }, onError: (error) => { sseSend(controller, "error", { error }); controller.close(); } }); } }); return new Response(readable, { headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-cache", Connection: "keep-alive", ...rlH } }); } return (env as any)[bindingName].get((env as any)[bindingName].idFromName(sid)).fetch("https://do/chat", { method: "POST", body: JSON.stringify({ content: message, conversationId: sid, images: body.images, model: body.model }), headers: { "Content-Type": "application/json" } }); }
  if (path === "/api/missions" && request.method === "GET") { const user = requireSession(session); return ok(await listMissions(env.DB, user.userId)); }
  if (path === "/api/missions" && request.method === "POST") { const user = requireSession(session); const body = await parseJson<any>(request); const goal = String(body.goal || "").trim(); if (!goal) return ok({ error: "goal required" }, 400); const mission = await createMission(env.DB, goal, body.projectId || null, user.userId); const rawSteps = Array.isArray(body.steps) ? body.steps : []; const steps = []; for (let i = 0; i < rawSteps.length; i++) { const step = rawSteps[i] || {}; if (!step.task) continue; steps.push(await addMissionStep(env.DB, mission.id, i, normalizeAgent(step.agent), String(step.title || `Step ${i + 1}`), String(step.task))); } if (steps.length) await setMissionStatus(env.DB, mission.id, "running", null, null, user.userId); return ok({ ...mission, status: steps.length ? "running" : mission.status, steps, userId: user.userId }, 201); }
  if (path.startsWith("/api/missions/") && path.endsWith("/status") && request.method === "PATCH") { const user = requireSession(session); const id = path.split("/")[3]; const body = await parseJson<any>(request); const status = String(body.status || "") as MissionStatus; if (!["queued", "planning", "running", "completed", "failed", "cancelled"].includes(status)) return ok({ error: "invalid status" }, 400); const updated = await setMissionStatus(env.DB, id, status, body.result ?? null, body.error ?? null, user.userId); if (!updated) return ok({ error: "Not found" }, 404); return ok(await getMission(env.DB, id, user.userId)); }
  if (path.startsWith("/api/missions/") && path.endsWith("/steps") && request.method === "POST") { const user = requireSession(session); const id = path.split("/")[3]; const body = await parseJson<any>(request); if (!body.task) return ok({ error: "task required" }, 400); const current = await getMission(env.DB, id, user.userId); if (!current.mission) return ok({ error: "Not found" }, 404); const index = Number.isInteger(body.index) ? body.index : current.steps.length; const step = await addMissionStep(env.DB, id, index, normalizeAgent(body.agent), String(body.title || `Step ${index + 1}`), String(body.task)); await setMissionStatus(env.DB, id, "running", null, null, user.userId); return ok(step, 201); }
  if (path.startsWith("/api/missions/") && path.includes("/steps/") && path.endsWith("/status") && request.method === "PATCH") { const parts = path.split("/"); const stepId = parts[5]; const body = await parseJson<any>(request); const status = String(body.status || "") as any; if (!["queued", "running", "completed", "failed"].includes(status)) return ok({ error: "invalid step status" }, 400); await setStepStatus(env.DB, stepId, status, body.result ?? null); return ok({ ok: true }); }
  if (path.startsWith("/api/missions/") && request.method === "GET") { const user = requireSession(session); const data = await getMission(env.DB, path.split("/")[3], user.userId); if (!data.mission) return ok({ error: "Not found" }, 404); return ok(data); }
  if (path === "/api/conversations" && request.method === "GET") { const user = requireSession(session); const r = await env.DB.prepare("SELECT * FROM conversations WHERE user_id = ? ORDER BY updated_at DESC LIMIT 100").bind(user.userId).all(); return ok(r.results); }
  if (path === "/api/conversations" && request.method === "POST") { const user = requireSession(session); const { agentType, title, projectId } = await parseJson<any>(request); const id = crypto.randomUUID(); await env.DB.prepare("INSERT INTO conversations (id, agent_type, title, project_id, user_id) VALUES (?, ?, ?, ?, ?)").bind(id, agentType || "nexus", title || "New conversation", projectId || null, user.userId).run(); return ok({ id }); }
  if (path.startsWith("/api/conversations/") && request.method === "GET") { const user = requireSession(session); const c = path.split("/")[3]; const conv = await env.DB.prepare("SELECT * FROM conversations WHERE id = ? AND user_id = ?").bind(c, user.userId).first(); if (!conv) return ok({ error: "Not found" }, 404); const msgs = await env.DB.prepare("SELECT * FROM messages WHERE conversation_id = ?").bind(c).all(); return ok({ conversation: conv, messages: msgs.results }); }
  if (path.startsWith("/api/conversations/") && request.method === "DELETE") { const user = requireSession(session); const c = path.split("/")[3]; const conv = await env.DB.prepare("SELECT id FROM conversations WHERE id = ? AND user_id = ?").bind(c, user.userId).first(); if (!conv) return ok({ error: "Not found" }, 404); await env.DB.prepare("DELETE FROM messages WHERE conversation_id = ?").bind(c).run(); await env.DB.prepare("DELETE FROM conversations WHERE id = ?").bind(c).run(); return ok({ ok: true }); }
  if (path === "/api/documents" && request.method === "POST") { const user = requireSession(session); const fd = await request.formData(); const file = fd.get("file") as File | null; if (!file) return ok({ error: "file required" }, 400); const id = crypto.randomUUID(); const key = `documents/${id}/${file.name}`; await env.BUCKET.put(key, file.stream()); await env.DB.prepare("INSERT INTO documents (id, source, source_key, title, status, user_id) VALUES (?, 'r2', ?, ?, 'pending', ?)").bind(id, key, file.name, user.userId).run(); await env.DOC_QUEUE.send({ documentId: id, source: "r2", sourceKey: key, title: file.name, userId: user.userId }); return ok({ documentId: id, status: "queued" }); }
  if (path === "/api/documents" && request.method === "GET") { const user = requireSession(session); const r = await env.DB.prepare("SELECT * FROM documents WHERE user_id = ? ORDER BY created_at DESC LIMIT 100").bind(user.userId).all(); return ok(r.results); }
  if (path === "/api/ingest" && request.method === "POST") { const user = requireSession(session); const { text, title } = await parseJson<any>(request); if (!text) return ok({ error: "text required" }, 400); const id = crypto.randomUUID(); const key = `documents/${id}/inline.txt`; await env.BUCKET.put(key, text); await env.DB.prepare("INSERT INTO documents (id, source, source_key, title, status, user_id) VALUES (?, 'upload', ?, ?, 'pending', ?)").bind(id, key, title || "Inline text", user.userId).run(); await env.DOC_QUEUE.send({ documentId: id, source: "r2", sourceKey: key, title: title || "Inline text", userId: user.userId }); return ok({ documentId: id, status: "queued" }); }
  if (path === "/api/search" && request.method === "POST") { requireSession(session); const { query } = await parseJson<any>(request); const emb = await env.AI.run(MODELS.embeddings.primary, { text: [query] }); const v = (emb as any).data?.[0] ?? []; const r = await env.VECTORIZE.query(v, { topK: 10, returnMetadata: "all" }); return ok({ query, results: r.matches ?? [] }); }
  if (path === "/api/ai-search" && request.method === "POST") { requireSession(session); const { query } = await parseJson<any>(request); try { return ok(await env.AI_SEARCH.search({ query })); } catch { return ok({ error: "AI Search not configured" }, 502); } }
  if (path === "/api/artifacts" && request.method === "GET") { const user = requireSession(session); const cId = url.searchParams.get("conversationId"); if (cId) { const r = await env.DB.prepare("SELECT * FROM artifacts WHERE conversation_id = ? ORDER BY created_at DESC").bind(cId).all(); return ok(r.results); } const r = await env.DB.prepare("SELECT * FROM artifacts ORDER BY created_at DESC LIMIT 100").all(); return ok(r.results); }
  if (path.startsWith("/api/artifacts/") && request.method === "GET") { requireSession(session); const a = await env.DB.prepare("SELECT * FROM artifacts WHERE id = ?").bind(path.split("/")[3]).first(); if (!a) return ok({ error: "Not found" }, 404); if (a.r2_key) { const obj = await env.BUCKET.get(a.r2_key as string); if (obj) return new Response(obj.body, { headers: { "Content-Type": "image/png" } }); } return ok(a); }
  if (path.startsWith("/api/images/") && request.method === "GET") { requireSession(session); const key = assertSafeObjectKey(path.slice("/api/images/".length)); const obj = await env.BUCKET.get(key); if (!obj) return new Response("Not found", { status: 404 }); return new Response(obj.body, { headers: { "Content-Type": obj.httpMetadata?.contentType || "image/png" } }); }
  if (path === "/api/models" && request.method === "GET") return ok({ chat: MODELS.chat, vision: MODELS.vision, imageGen: MODELS.imageGen, stt: MODELS.stt, tts: MODELS.tts, embeddings: MODELS.embeddings, agentModels: AGENT_MODELS });
  if (path === "/api/stats" && request.method === "GET") { const t = await env.DB.prepare("SELECT COUNT(*) as count, SUM(input_tokens) as input_tokens, SUM(output_tokens) as output_tokens FROM usage").first(); const byA = await env.DB.prepare("SELECT agent_type, COUNT(*) as count, SUM(input_tokens) as input_tokens, SUM(output_tokens) as output_tokens FROM usage GROUP BY agent_type").all(); return ok({ total: t, byAgent: byA.results }); }
  if (path === "/api/projects" && request.method === "GET") { const user = requireSession(session); const r = await env.DB.prepare("SELECT * FROM projects WHERE user_id = ? ORDER BY created_at DESC").bind(user.userId).all(); return ok(r.results); }
  if (path === "/api/projects" && request.method === "POST") { const user = requireSession(session); const { name, description, systemPrompt } = await parseJson<any>(request); if (!name) return ok({ error: "name required" }, 400); const id = crypto.randomUUID(); await env.DB.prepare("INSERT INTO projects (id, name, description, system_prompt, user_id) VALUES (?, ?, ?, ?, ?)").bind(id, name, description || "", systemPrompt || "", user.userId).run(); return ok({ id, name }); }
  if (path.startsWith("/api/projects/") && request.method === "GET") { const user = requireSession(session); const id = path.split("/")[3]; const p = await env.DB.prepare("SELECT * FROM projects WHERE id = ? AND user_id = ?").bind(id, user.userId).first(); if (!p) return ok({ error: "Not found" }, 404); return ok(p); }
  return new Response("Not found", { status: 404, headers: rlH });
}
